### ISSUE TITLE
Basecamp-classic API and Express.js

### ISSUE THREAD

**Issue by chrsfshr** [nodeschool/austin#1]
Can someone explain to me how to use this module for basecamp-classic api. I'm trying to display a list of projects in the browser but I keep getting the error Cannot/Get. I'm using express.js. The example they give isn't helping me much as I'm new to node and express.

https://www.npmjs.org/package/basecamp-classic

My Code:

//Require
var express = require('express');
var app = express();
var Basecamp = require('basecamp-classic');
var hbs = require('hbs');

//Server
app.listen(3000);

//App
app.set('view engine', 'html');
app.engine('html', hbs.__express);

var bc = new Basecamp(
  'https://YOURCOMPANY.basecamphq.com',
  'API KEY'
);

console.log(bc);

module.exports = function(req, res) {
  bc.todoLists.all(function(err, lists){
    if(err) {
      console.log(err);
      res.send('there was a problem');
    } else {
      // render the todo template and pass it our lists object
      res.render('todo', {
        todoLists: lists
      });
    }
  });
}

**Comment by dylants** [comment]
@chrsfshr Have you been able to find a solution to the issue you posted above?  If not, maybe we can still help -- what is the problem as of now?

**Comment by dylants** [comment]
I believe this to be resolved, please re-open if not the case, thanks!
