### ISSUE TITLE
Mentor Registration for NodeSchool at NodeInteractive 2016

### ISSUE THREAD

**Issue by cdnadmin** [nodeschool/austin#15]
**Please note that the following could change as we get closer to the event.**

This session of Austin NodeSchool will be during [Node Interactive North America 2016](http://events.linuxfoundation.org/events/node-interactive), which is taking place in Austin, TX, USA.
## Notes:
- Since this is a special event, we do _hope_ that you've mentored at a NodeSchool before and that you're excited to engage with attendees. 
- Having completed [some of the core and/or elective workshoppers](http://nodeschool.io/#workshopper-list) is a great bonus.
- We're accepting up to 12 mentors for this event.  
- Please review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
- Please arrive 30 minutes early so we can get setup and have our mentor meeting.
- All mentors are also being asked, but not required, to please consider [volunteering as MCs](https://github.com/nodeschool/austin/issues/17) for the break-out sessions. 

Wanna get involved? Please comment in here to get involved or ask questions.
### AM Session
- [x] Julia Jacobs (@jewelsjacobs)
- [x] Ian White (@ianwhitedeveloper)
- [x] Andrew Stalick (@andystalick)
- [x] Kyle Smith (@knksmith57)
- [x] Stefan von Ellenrieder (@stefanmve)
- [x] Scott Beaudreau (@scottbea)
### PM Session
- [x] Julian Duque (@julianduque)
- [x] Stefan von Ellenrieder (@stefanmve)
- [x] Avi Das (@avidas)
- [x] Ross Kukulinski (@rosskukulinski)
- [ ] Open Slot
- [ ] Open Slot
## Organizers and Volunteers:
- [x] Monico Moreno (@cdnadmin)
- [x] Avi Das (@avidas)

**Comment by rosskukulinski** [comment]
@cdnadmin what are the times for AM vs PM session?

**Comment by julianduque** [comment]
@cdnadmin I'm in for PM session

**Comment by cdnadmin** [comment]
@rosskukulinski we're still working out the fine details, but a good guess would be 9-12 & 1-4

@julianduque ur in!  thx for the help!

**Comment by andystalick** [comment]
I'll be volunteering in one of the RMN slots.

**Comment by cdnadmin** [comment]
Got ya on there, @andystalick !  Thx for volunteering!  :-)

**Comment by knksmith57** [comment]
Heya, I'll be taking the other RMN slot. Thanks!

**Comment by cdnadmin** [comment]
Thx for volunteering, @knksmith57 !  Gotcha on there!

**Comment by dylants** [comment]
@cdnadmin I'm available for whatever you need help with, and can do any or both time slots 😄

**Comment by cdnadmin** [comment]
Got ya on there @dylants   Thx, man!  👍

**Comment by dylants** [comment]
Do we have a better understanding of the days and times volunteers are needed? I know Node.js Interactive is November 29th - December 2nd. Is the NodeSchool session scheduled for multiple days or a single day? And are the timeframes indeed 9-12 and 1-4?

Just wondering as we get closer, knowing what time we'll need to be there (and make sure work knows that as well 😄 ).

Thanks!

**Comment by cdnadmin** [comment]
Hey, @dylants sorry about the delayed reply....so, NodeSchool mentors are needed only for Tue, 11/29, for either AM or PM mentoring.  The NodeSchool event will only be on Tue 11/29.  

I'll try to get the time frames solidified but would tentatively plan for 9-12 & 1-4, depending on what slot you're in.

All that being said, we had 6 slots for MC (aka emcee) volunteers (from the NodeSchool mentors) to help during break-out sessions on Tue (11/29) and Wed (11/30).  All 6 spots have been filled, but if anyone wants to be in stand by in case someone doesn't show, we can probably do that. 

Hope that helps!  
--Monico

**Comment by dylants** [comment]
@cdnadmin Thanks! That sounds great, looking forward to Tuesday!

**Comment by rosskukulinski** [comment]
@cdnadmin I volunteered as an MC for Tuesday afternoon, so moving myself to be a morning mentor.

**Comment by cdnadmin** [comment]
Hi, y’all,

Many apologies for having to change schedules around, but the ATX NodeSchool event happening at NINA this week, is going to be on **_Wed 11/30_**, instead of Tue.  Please feel free to adjust your MC schedules (if relevant) and get with me on the GH issue if you need to swap AM/PM.  

The “hours of operation” for the ATX NodeSchool event are **_9am-12pm and 1pm-3pm_**.

Again, many apologies for this, and THANK YOU for helping with this!  ;-) 

Sincerely,
Monico A. Moreno

PS: @rosskukulinski I sent this as an email as well to all, but I didn't have yours, so, hopefully you get this in time.  I'll ping ya on Twitter too just to cover all bases.  ;-)

**Comment by scottbea** [comment]
I can help. I a Principal Architect at HomeAway in Austin. I've done Node for many years, in both a startup and while at Amazon (in the AWS Lambda team). I'd love to help out in the 9-12 am slot. I have a conflict from 1-2 pm is all. Happy to do MC too.

**Comment by cdnadmin** [comment]
hi, @scottbea, thx for offering.  You're on the AM session.  Also, if ur already in town at the JW Marriott right now (5:52PM CST), we are having an MC meeting at 6:30 on the 4th floor.  

Btw, I work for Patrick R. at HomeAway at the domain!  ;-)  Looking forward to meeting you!

**Comment by dylants** [comment]
I'm very sorry @cdnadmin, but I have a conflict on Wednesday and won't be able to make it. Wish you guys the best of luck, sorry again I couldn't be there!

**Comment by cdnadmin** [comment]
Not a problem @dylants!  We should be able to cover.  Thx for the heads up! 👍🏼
