### ISSUE TITLE
Select Workshoppers for NodeSchool at Node Interactive 2016

### ISSUE THREAD

**Issue by cdnadmin** [nodeschool/austin#16]
Begin discussion about what [NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) to use during [Node Interactive North America 2016](http://events.linuxfoundation.org/events/node-interactive)

(please note that below workshoppers could change as we continue to discuss)
### Confirmed Workshoppers
- [x] LearnYouNode
- [x] Javascripting

### Confirmed Workshoppers
- [x] How to NPM
- [x] stream-adventure

Lockdown of these will occur sometime early November.

**Comment by hackygolucky** [comment]
The structure we've talked about is two 'sessions' happening over the course of the day. I'd say offering two different workshoppers in the morning and two in the afternoon might be nice, each session having one more advanced, one more beginner level workshopper. 

Is offering two workshoppers in the same session going to be chaotic?

**Comment by cdnadmin** [comment]
I think having two workshoppers per session is cool...that way there is more of a spread across expertise levels.  Attendees will also have the freedom of partially working on one, then jump into the other workshopper if they want.  

> Is offering two workshoppers in the same session going to be chaotic?

I don't think it'll be chaotic; mentors will be well versed on the four workshoppers we decide on, so, they'll be good.  One thing we might want to mention during, in regards to avoiding chaos, is that attendees working on the same workshopper might sit close together--and hopefully pair up if nec.  **This also has the added benefit of getting attendees to work together and interact**!  ;-)

**Comment by cdnadmin** [comment]
At the risk of making a unilateral decision, in the absence of much activity here, I went ahead and added Javascripting and stream-adventure modules above.  

If anyone would like to discuss changing these, please do let us know ASAP.
