### ISSUE TITLE
Call for Breakout Session MCs at Node Interactive 2016

### ISSUE THREAD

**Issue by cdnadmin** [nodeschool/austin#17]
This is for NodeSchool mentors.  These Masters of Ceremony will introduce NodeInteractive speakers and ensure that speakers are on time etc.   More details soon. 
## Confirmed MCs
- [x] Monico Moreno (@cdnadmin)
- [x] Julia Jacobs (@jewelsjacobs)
- [x] Ian White (@ianwhitedeveloper)
- [x] Julian Duque (@julianduque)
- [x] Stefan von Ellenrieder (@stefanmve)
- [x] Avi Das (@avidas)

## All slots filled!

 Thx everyone!  Please stand by for details, etc.

**Comment by cdnadmin** [comment]
@hackygolucky et al do we have a number of MCs to shoot for?

**Comment by hackygolucky** [comment]
6, I believe.
