### ISSUE TITLE
lololodash exercise 3 issue on node-inspector with node v.10.33?

### ISSUE THREAD

**Issue by sinkingshriek** [nodeschool/austin#4]
I don't know if this is happening to just me or everyone else who uses `node-inspector` to debug their code but I've been consistently getting this error and I don't know why.

My code is simply :- 

    var _ = require('lodash');
    var workers = function(collection) {
        return _.forEach(collection, function(col) {
           debugger;
		   console.log(col);
        });
    };
    debugger;
    workers({
            Hamburg:{population: 1.698 }, 
            Strasbourg: {population: 0.272 }, 
            Rome:{ population: 2.753 }, 
            Dublin:{ population: 0.528}
     });
    module.exports = workers;

It breaks everytime inside the callback of `forEach`. And just for the heck of it I upgraded to node v.11.33 and things ran just fine. 

I guess what I wanted to know was if anybody is having the same issue as I am or is it something that I'm doing wrong?

**Comment by michaelhayman** [comment]
I had the same error when I was using `console.log`, particularly in connection with Firebase.  I had success using `require('util')` and `util.log` instead of `console.log`.

**Comment by hamsterbacke23** [comment]
thanks @michaelhayman  `util.log` instead of `console.log` did it for me as well

**Comment by Earl-Brown** [comment]
I installed Node v 11 (a beta release), and that fixed this issue.  There were a couple of changes I needed to make to Express libraries to protect against assumptions, but I've got my Node-Inspector working now.

**Comment by dylants** [comment]
I'm closing this issue because I believe this issue has been addressed?  Please feel free to re-open if that is not the case.

**Comment by sinkingshriek** [comment]
@Earl-Brown which version of node v11 was it exactly? @dcbartlett tested on couple of patched version of node v11 and it was breaking for him and me too.

**Comment by offero** [comment]
I am having this same issue with node-inspector... definitely open a ticket with them if you can describe the problem well.

**Comment by sinkingshriek** [comment]
Reopening.

**Comment by sinkingshriek** [comment]
This has now been [fixed](https://github.com/node-inspector/node-inspector/issues/517#issuecomment-69439640).
