### ISSUE TITLE
Test not passing on lololodash exercise 9.

### ISSUE THREAD

**Issue by sinkingshriek** [nodeschool/austin#5]
So, after numerous tries with trailing spaces and line-breaks fixes the exercise on "Todo Template" test is still not passing.

![screenshot from 2014-12-10 21 38 59](https://cloud.githubusercontent.com/assets/682197/5388744/33b6b994-80b6-11e4-9935-f895bd5b08d0.png)

To test if there's anymore trailing spaces or line-breaks I even checked it on ST. Shows fine by ST. Is this a known issue?
![passing](https://cloud.githubusercontent.com/assets/682197/5388736/1fbf0a2c-80b6-11e4-8365-9a703292574f.png)

Just FYI, this is the output when I run `lololodash run` not `lololodash verify`.

**Comment by dylants** [comment]
@sinkingshriek Are you still seeing this issue?  If so, would you mind posting the code you wrote which generates this solution?  We can try to run it locally and see if we see the same problem.

**Comment by sinkingshriek** [comment]
Sure. Not really a clean solution but here's what I have.

    var _ = require('lodash');
    var render = "<ul>\
        <% _.forEach(collection, function(todos, key){%>\n\
        <li><%=key %>\
            <%if(_.size(todos)){ %>\n\
                <ul><% _.forEach(todos, function(todo){ %>\
                    <li>\
                        <% if(( Date.parse(todo.date) - Date.now()) > (2*24*60*60*1000)){ %>\
                            <b>Urgent</b>\
                       <%}%>\
                       <%=todo.todo%>\
                  </li>\n\
               <% });%>\
               </ul>\n\
          <% } %>\
      </li><% }); %>\n\
    </ul>";
    
    var workers = function(collection) {
        var obj2 = {};
        _.forEach(collection, function(todos, key) {
            obj2[key] = _.sortBy(todos, 'date');
        });
        return _.template(render, {
            collection: obj2
        });
    };

**Comment by sinkingshriek** [comment]
I have a feeling that there's something wrong with the `Date` logic for the `Urgent` tag but it is kinda nightmare to debug in template. If someone knows how to easily debug then please let me know.

**Comment by dylants** [comment]
@sinkingshriek I looked through the code you wrote and made some changes to get it working.  Here's a high level overview of the changes I made:

*   I pulled out the `Date` calls to a function `isUrgent` and passed it in the `_.template` call as an `imports` (this was brought up in the description for this problem).  I also reversed the check from a `>` to a `<`.
*   I had problems with the multi-line formatting you had chosen for the `render` template variable, so I just closed the quote on each line and added to the string on the next line.  This seemed to be causing some spacing issues when I ran it, so I thought it would just be easier to manage the template in this way.
*   I had to change `Urgent` to `URGENT` and add a space after the word to match the problem output.
*   And finally, the check for `_.size(todos)` wasn't necessary and did cause a problem with one of the verify solutions so I took that out (the `_.forEach` will only loop if it's got something in it).

Below is the solution I was able to verify:

    "use strict";

    var _ = require('lodash');

    var isUrgent = function(date) {
        return ( Date.parse(date) - Date.now()) < (2*24*60*60*1000);
    };

    var render = "<ul>\n" +
        "<% _.forEach(collection, function(todos, key){%>" +
        "<li><%=key %>\n" +
            "<ul><% _.forEach(todos, function(todo){ %>" +
                "<li>" +
                    "<% if(isUrgent(todo.date)){ %>" +
                        "<b>URGENT</b> " +
                   "<%}%>" +
                   "<%=todo.todo%>" +
              "</li>\n" +
           "<% });%>" +
           "</ul>\n" +
      "</li>\n" +
      "<% }); %>" +
    "</ul>";

    var workers = function(collection) {
        var obj2 = {};
        _.forEach(collection, function(todos, key) {
            obj2[key] = _.sortBy(todos, 'date');
        });
        return _.template(render, {
            collection: obj2
        }, {
            imports: {
                isUrgent: isUrgent
            }
        });
    };

    module.exports = workers;

Hope that works for you!

**Comment by sinkingshriek** [comment]
>I pulled out the Date calls to a function isUrgent and passed it in the _.template call as an imports (this was brought up in the description for this problem). I also reversed the check from a > to a <.
Oops, I might have switched `Date.now() - Date.parse(todo.date)` with `Date.parse(todo.date) - Date.now()` and forgot to switch the operator.

Thank you for taking a look.

**Comment by dylants** [comment]
No problem, glad it helped!

**Comment by srperetz** [comment]
I'm completely stymied, and I'm hoping someone can help me out.  My solution to this problem looks to be essentially identical to the one posted above by @dylants, and the one posted by @mdunisch [here](https://github.com/mdunisch/lololodash/blob/master/exercises/9_todo_template/solution/solution.js).  Yet my solution fails when I run it, returning only `undefined`.

Any suggestions would be immensely appreciated.

Here's my code:

```
"use strict";

var _ = require("lodash");

var worker = function(toDoData) {
   if (!(toDoData)) return "";

   var isUrgentDate = function(dateStr) {
      return (new Date(dateStr).getTime() -  new Date().getTime()) < (2 * 24 * 60 * 60 * 1000);
   }

   _.forEach(toDoData,
         function(toDoList, person) {
            toDoData[person] = _.sortBy(toDoList, 'date');
         });

   var toDoHtml = "<ul>\n" +
      "<% _.forEach(toDoCollection, %>" +
         "<% function(toDoList, personName) { %>" +
            "<li><%= personName %>\n" +
            "<ul>" +
            "<% _.forEach(toDoList, %>" +
               "<% function(toDo) { %>" +
                  "<li>" +
                  "<% if (isUrgentDate(toDo.date)) { %><b>URGENT</b> <% } %>" +
                  "<%= toDo.todo %>" +
                  "</li>\n" +
               "<% }); %>" +
            "</ul>\n" +
            "</li>\n" +
         "<% }); %>" +
      "</ul>\n";

   return _.template(toDoHtml, { toDoCollection: toDoData }, { 'imports': { 'isUrgentDate': isUrgentDate } });
}

module.exports = worker;
```

**Comment by srperetz** [comment]
I got an answer on this [here](https://github.com/nodeschool/discussions/issues/900#issuecomment-71971187), in case anyone is wondering :)

**Comment by sinkingshriek** [comment]
This is good to know. Not a big fan of templating from lodash or underscore tbh.
