### ISSUE TITLE
Mongoose and MongoDB write issue

### ISSUE THREAD

**Issue by Kalevera** [nodeschool/austin#9]
The issue i'm having is, mongoose appears to attempt a write process to the MongoDB but fails. If I previously drop the collection in MongoDB I can see the collection being created but it doesn't show the document that i'm attempting to write to the DB. it's either an issue with how the mongoose schema is written, or a configuration issue with mongoDB i suspect the former but am unsure. 

the mongoose schema i'm using is this 
````
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var dishesSchema = new Schema({dish:{
	user_name: {type: String, default: 'Tree of life'},
	location: {type:String},
	geo:{type:Schema.Types.Mixed,
		gtype: {type:String, default: "Point"}, 
		coordinates: {type:[Number],index:'2dsphere'}
	},
	title: {type: String, match: /[a-z]/},
	ingdts: {type:String},
	cost:{type: Number, index: true}
	//image: {
    //	mime:  {type:String},
    //	bin: Buffer,
    //	}

}});

var Dish = mongoose.model('Dish', dishesSchema)

module.exports={Dish:Dish};
````
I then apply my JSON that's been paresed by body parser in express and assign the corresponding values from req.body.title, etc... to the schema and then use mongoose to create the document in the collection. for some reason ever since I added the sub-document geo to the schema it wont write, any thoughts? 

Below is the map router which sends the information to Mongo

````
var Map = require('../public/js/map').Map;
var bodyParser = require('body-parser');
var parser = bodyParser.json();

function getMaps(res){
	Map.find('maps', function(err, maps){
		// if there is an error retrieving, send the error. nothing after res.send(err) will execute
		if (err){
			res.send(err)
		}else{
			res.json(maps); // return all dishes in JSON format
		}	
	})
};


module.exports = function(app) {

	// api ---------------------------------------------------------------------
	// get all dishes
	app.get('/js/map', function(req, res) {
		// use mongoose to get all dishes in the database
		getMaps(res);
	});

	// create map and send back all dishes after creation
	app.post('/js/map', parser, function(req, res) {

    var f = req.body.coordinates;  

		// create a dish, information comes from AJAX request from Angular
    console.log("hey the map request has this in it: "+ f);
		Map.create({ /*"map.properties": b,*/ "map.coordinates":[f] /*,"dish.geo.coordinates":f*/},
		 function(err, map) {
			if (err){
				res.send(err);
			}else{
				// get and return all the maps after you create another
				getMaps(res);
			}

		});

	});

	// delete a map
	app.delete('/js/map:map_id', function(req, res) {
		Map.remove({
			_id : req.params.map_id
		}, function(err, map) {
			if (err){
				res.send(err);
      }else{
			getMaps(res);
      }
    });
	});
};
````
Here is the Dish router as you can see they are identical

````
var Dish = require('../public/js/dish').Dish;
var bodyParser = require('body-parser');
var parser = bodyParser.json();

function getDishes(res){
	Dish.find('dishes', function(err, dishes){
		// if there is an error retrieving, send the error. nothing after res.send(err) will execute
		if (err){
			res.send(err)
		}else{
			res.json(dishes); // return all dishes in JSON format
		}	
	})
};


module.exports = function(app) {

	// api ---------------------------------------------------------------------
	// get all dishes
	app.get('/js/dish', function(req, res) {
		// use mongoose to get all dishes in the database
		getDishes(res);
	});

	// create dish and send back all dishes after creation
	app.post('/js/dish', parser, function(req, res) {

		var b = req.body.title;
		var c = req.body.cost;
		var d = req.body.ingdts;
		var e = req.body.location;
 

		// create a dish, information comes from AJAX request from Angular
    console.log("hey the dish request has this in it: "+ b,c,d,e,f);
		Dish.create({"dish.title": b, "dish.cost": c, "dish.ingdts": d, "dish.location": e},
		 function(err, dish) {
			if (err){
				res.send(err);
			}else{
				// get and return all the dishes after you create another
				getDishes(res);
			}

		});

	});

	// delete a dish
	app.delete('/js/dish:dish_id', function(req, res) {
		Dish.remove({
			_id : req.params.dish_id
		}, function(err, todo) {
			if (err){
				res.send(err);
      }else{
			getDishes(res);
      }
		});
	});
};
````

**Comment by dylants** [comment]
In the beginning of your post, you're unsure if this is a configuration issue with MongoDB, however later you said that the schema and setup you have worked until you added the `geo` part to the schema.  If this is true, then I don't suspect you have any MongoDB configuration or connection issues (since you are able to write prior to this add).

I don't have any experience using the geospatial indexing within Mongo, do you know if you've specified the data correctly?  Perhaps this is a problem just with that block, maybe try isolating that out and testing that works correctly?

**Comment by evanlucas** [comment]
is the `geo` property supposed to be an object? If so, you do not need to specify the type for it. If coordinates should be an array, the square brackets should be outside the object vs the type like `[{ type: Number, index: '2dsphere' }]`

So, the whole object would like like:

```
geo:{
  gtype: { type:String, default: "Point" }, 
  coordinates: [{ type: Number, index:'2dsphere' }]
}
```

**Comment by Kalevera** [comment]
@dylants  Thanks I isolated the geoJSON object and it appears to be setup correctly when I compare it to my other app.post, app.get methods. now I can see the maps collection appear if I previously drop the collection but it doesn't write the document. The Only thing i'm doing differently than the other collections is I changing the index to 2dsphere. 

@evanlucas you are right i was trying to make coordinates an array, I made it an array because it looks like the coordinats need to be stored as a pair in MongoDB. I also took out Schema.types.mixed it wasn't necessary since geo is supposed to be geoJSON document. I was hoping to use the 2dsphere capabilities of MongoDB to run $near queries which is why i'm changing the index.  

Maybe I didn't create the collection correctly? I followed this Doc to create the collection in Mongo first using coordinates as the location field [MongoDoc create 2dsphere].(http://docs.mongodb.org/manual/tutorial/build-a-2dsphere-index/).

I did do one thing that may be causing the issue. in the user controller i'm setting GPS to the mapservice, I then call that position from map service in the dishcontroller then send the dish reqs to the dish route and map req to map route. I don't think it causes an issue since they're async. Thoughts? I can post more code if needed.

**Comment by Kalevera** [comment]
got it working @evanlucas  that was the issue I was able to write to the DB afterwards with some issues, once I was able to go through every piece of code that handles that object from front to back I was able to find two small typos that were not assigning the GPS values. Thanks again @evanlucas and @dylants.
